
# Site settings
title: "AweSome Blog"
description: "Aru's Daily Page"
keywords: 'DeepLearning, NeuralNetwork'
url: "https://aruie.github.io" # your host
author: "Aru"


name: 'aruie'
NickName: 'Aru'
webtitle: "Aru's Blog"
bio: 'your awesome bio'
about: true
aboutyou: 'your introduction'
portraits: '/assets/profile.jpeg' # your portraits image file path

# paginate
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
# kramdown:
#   input: GFM
################# rouge????
highlighter: rouge
#################
pygmentsTheme: 'default'


# disqus
disqus: false
disqus_url: '' 

Gitment: false
Gitment_owner: ''  
Gitment_repo: ''  
client_id: ''  
client_secret: '' 

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
#social-share: true
#social-share-items: ['twitter', 'facebook']

google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)



